{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "pod4.fullname" . }}-hpa
  namespace: {{ .Release.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "pod4.fullname" . }}-deployment
  {{- if and .Values.autoscaling (hasKey .Values.autoscaling "minReplicas") (hasKey .Values.autoscaling "maxReplicas") }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- end }}
  metrics:
    {{- if and .Values.autoscaling (hasKey .Values.autoscaling "targetCPUUtilizationPercentage") }}
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if and .Values.autoscaling (hasKey .Values.autoscaling "targetMemoryUtilizationPercentage") }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}